name: Rust

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  tag-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
        - stable
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt-get update
          sudo apt-get -y install libpulse-dev libudev-dev #External dependencies
          while read -r cmd
          do
            eval sudo $cmd

          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "22.04"))')          

      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.tollchang }}

      - run: cargo install cargo-deb

      - name: Build and Package
        run: cargo build --release --verbose && cargo deb -p mewture_daemon

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.deb"
