name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
        - stable

    steps:
      - uses: actions/checkout@v3
        with:
          repository: acheronfail/pulse-rs
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.tollchang }}
      - name: Build and Package
        run: cargo build --release --verbose && cargo deb -p mewture_daemon
      # - name: Run tests
        # run: cargo test --verbose
